# Site settings
title: Andy Coravos
tag_text: Andy Coravos
description: The party is now. On a marvelous adventure.
url: "https://andreacoravos.com"  # Use your custom domain instead of GitHub Pages URL
baseurl: ""  # Should remain empty for GitHub Pages custom domains

# Build settings
markdown: kramdown
sass:
  style: compressed

# Google services
google_analytics: G-SN83VPQTEX

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap  # Added to generate sitemap.xml

# Exclude unnecessary files
exclude:
  - README.md
  - config.ru
  - Gemfile
  - Gemfile.lock
  - vendor
